## week02_homework
基本的Python一題，Numpy與Pandas各一題

### Python

### 交割日期:  
    假設投資人在 T日 購買一張股票， T日稱為成交日期。
    不過投資人必須要等到 T+1(隔日) 才會收到這張股票。
    若是要賣這張股票，也是T+1(隔日)才能賣出。
    而這張股票必須支付的股款，必須在T+2早上10點前存入證券交割帳戶，
    T+2 也就是所謂的交割日期。
    若是T+2早上10點後，戶頭裡面的餘額不夠支付，就會發生違約交割的情形。

### 股票買賣交易流程:

| T日(今天) | T+1日(明天) | T+2日(後天10：00) |
| :-----: | :-----: | :-----: | 
| 購買(賣出)股票 | 取得(失去)股票 | 支出(收入)股款 |


### 作業一:
>每當我們成功買進股票時，券商發送訊息會告知成交的相關訊息，  
請設計一程式，將成交回報的字串處理過後，輸出相關的交割資訊來提醒投資人。  

    input:  
    "於 7/15 2330 限價 581元  盤中零股現買 20股 已成交"   
    output: 
    "您於 7/15 購買 2330，每股 581元 20股"  
    "提醒您交割日期為 7月17日 10:00，交割款項為 11637元!"

備註:   
交割款項 = 成交價格 + 券商手續費  
成交價格 = 581(成交價) * 20(股數)  
券商手續費 = 成交價格 * 0.1425%  


In [97]:
data = input()
s = data.split(' ')
#print(s)
print("您於", s[1], "購買", s[2], "，每股", s[4], '共', s[6])

day = s[1].split('/')
if int(day[1]) + 2 < 31:
    day[1] = int(day[1]) + 2
else:
    day[0] = int(day[0]) + 1
    day[1] = int(day[1]) + 2 - 31
price = float(s[4].replace('元',''))
#print(price)
num = int(s[6].replace('股',''))
s_price = round(price * num * 0.001425) 
print("提醒您交割日期為", day[0], '月', day[1], "，交割款項為 ", price*num+s_price, "元!" )

於 7/15 2330 限價 581元 盤中零股現買 20股 已成交
您於 7/15 購買 2330 ，每股 581元 共 20股
提醒您交割日期為 7 月 17 ，交割款項為  11637.0 元!


請寫一個程式，要求使用者輸入每股成交金額與買入張數(中間以空格區分)，

然後程式會輸出交易手續費(取整數計算)，再輸出交割款項。

備註:
    交割款項 = 交易金額 + 交易手續費
    交易金額 = 每股成交金額 * 交易股數(1張股票為1000股)
    交易手續費 = 交易金額 * 券商手續費(0.1425％)
  
    範例輸入1：
        15.67 3
    範例輸出1：
        67
        47077
    範例輸入2：
        581 2
    範例輸出2：
        1656
        1163656    
        
---

* 對於input的處理: **資料型態**為字串!
* 字串與串列的轉換: .split(' ')

In [2]:
datas = input()
#print(datas)
data = datas.split(' ')
#print(data)
price = float(data[0])
num = int(data[1]) * 1000
prices = price * num
print(prices * 0.001425)
s_price = round(prices * 0.001425)
print(s_price)
print(int(prices + s_price))

104.5 6
893.475
893
627893


### Numpy

1. 今有一班級共4n個人(n>0)，老師按修課序號將全班分成n組。
2. 規定每一組的第一人是組長，總成績會額外加5分，超出100以100計。
3. 每組的平均成績大於80時，整組的總成績會額外加2分，超出100以100計。
4. 全班按照n*4的陣列且照組別依下表安排教室座位。

請寫一個程式，要求使用者輸入考試的4n筆成績（整數），使用者輸入一個-1表示完成這次考試成績的輸入。  

然後程式會輸出交易手續費(取整數計算)，再輸出交割款項。

> 請設計一程式，先輸入
程式中請按教室座位先輸出考試全班的成績（以整數輸出），然後再輸出加分過後的成績，最後再輸出等第成績(含組長額外加分，)。

**成績換算**
    90分以上為A
    80分以上為B，類推...
    60分以下為E

    範例輸入1：
    70
    99
    80
    85
    96
    50
    46
    61
    -1
    範例輸出1：
    [[70 99 80 85]
     [96 50 46 61]]

    [[ 77. 100.  82.  87.]
     [100.  50.  46.  61.]]

    [['C' 'A' 'B' 'B']
     ['A' 'E' 'E' 'D']]
---
直行橫列

* 迴圈與input與走訪Numpy
* 串列的處理與新增資料: .append()
* Numpy的應用: np.array(串列).reshape(列,行)
* Numpy的加總: np.sum(data, axis = 1) 
    * 1:列;0:行
* 注意: Numpy中的資料型態都必須是一樣的矩陣!

In [18]:
import numpy as np 
data1 = []
n = 0
i = eval(input())
while(i != -1):
    data1.append(i)
    i = eval(input())
    n += 1
num1 = np.array(data1).reshape(int(n/4),4)

print(num1)

add = np.sum(num1, axis = 1)
add = add/4
#print(add)
for i in range(len(add)):
    if add[i] > 80:
        add[i] = 2
    else:
        add[i] = 0
#print(add)
add = add.reshape(int(n/4),1)
#print(add)
sorce = num1 + add 
print()
#print(sorce)

grade = np.full(int(n),'A').reshape(int(n/4),4)

for i in range(int(n/4)):
    for j in range(4):
        if(j==0):
            sorce[i][j] += 5
        if(sorce[i][j]> 100):
            sorce[i][j] = float(100)
        if sorce[i][j] >= 90:
            grade[i][j] = 'A'
        elif sorce[i][j] >= 80:
            grade[i][j] = 'B'
        elif sorce[i][j] >= 70:
            grade[i][j] = 'C'
        elif sorce[i][j] >= 60:
            grade[i][j] = 'D'
        else:
            grade[i][j] = 'E'
print(sorce)
print()
print(grade)
#70 99 80 88 96 50 46 61 -1
#94 89 84 76 99 65 45 77 55 80 99 73 -1

94
89
84
76
99
65
45
77
55
80
99
73
-1
[[94 89 84 76]
 [99 65 45 77]
 [55 80 99 73]]

[[100.  91.  86.  78.]
 [100.  65.  45.  77.]
 [ 60.  80.  99.  73.]]

[['A' 'A' 'B' 'C']
 ['A' 'D' 'E' 'C']
 ['D' 'B' 'A' 'C']]


In [5]:
import numpy as np
o=[]
i=0
while True:
    x=int(input())
    if x==-1:
        break
    o.append(x)
    i+=1
r=np.array(o).reshape(-1,4)
#1
print(r)
print()

r[:,0]+=5
r[r>100]=100
aver=np.mean(r,axis=1)
r[aver>80]+=2
r[r>100]=100
#2
print(r)
print()
bins=np.array([60,70,80,90])
inds=np.digitize(r,bins)
level=['E','D','C','B','A']
#grade=map(lambda x:level[x],ind)
#print(np.array(grade))
vf=np.vectorize(lambda x:level[x])
#3
print(vf(inds))
#94 89 84 76 99 65 45 77 55 80 99 73 -1

94
89
84
76
99
65
45
77
55
80
99
73
-1
[[94 89 84 76]
 [99 65 45 77]
 [55 80 99 73]]

[[100  91  86  78]
 [100  65  45  77]
 [ 60  80  99  73]]

[['A' 'A' 'B' 'C']
 ['A' 'D' 'E' 'C']
 ['D' 'B' 'A' 'C']]


### pandas 

> 請設計一程式分析2330在7月與8月的表現，讀取 [2330.csv](2330.csv) 檔後計算出每月平均股價(收盤價)、當月的最高價及成交量(月總和) 

    EX:
    7 月的平均股價為: 370.74  元
    當月的最高價為:   466.5  元
    本月成交量為:  1468402  張

    8 月的平均股價為: 429.67  元
    當月的最高價為:   453.5  元
    本月成交量為:  1001180  張
---
* pandas的讀檔
* pandas取資料,loc與iloc
* pandas與numpy的轉換

In [82]:
import pandas as pd
import numpy as np

data = pd.read_csv('2330.csv')
#print(data.head())
data1 = data.iloc[:23,:]
Close = np.array(data1['Close'])
High = np.array(data1['High'])
Volume = np.array(data1['Volume'])
avg = np.sum(Close)/len(Close)
print("7 月的平均股價為:", round(avg,2), " 元")
print("當月的最高價為:  ", np.max(High), " 元")
print("本月成交量為: ",np.sum(Volume), " 張\n")
data2 = data.iloc[23:,:]
Close = np.array(data2['Close'])
High = np.array(data2['High'])
Volume = np.array(data2['Volume'])
avg = np.sum(Close)/len(Close)
print("8 月的平均股價為:", round(avg,2), " 元")
print("當月的最高價為:  ", np.max(High), " 元")
print("本月成交量為: ",np.sum(Volume), " 張\n")

7 月的平均股價為: 370.74  元
當月的最高價為:   466.5  元
本月成交量為:  1468402  張

8 月的平均股價為: 429.67  元
當月的最高價為:   453.5  元
本月成交量為:  1001180  張



In [27]:
import pandas as pd
import numpy as np
data = pd.read_csv('2330.csv')
print(type(data))
print(data.head())


Open = data.Open
print()
print(type(Open))
print(Open.head())

s = Open.sum()
print()
print(s)

a = np.array(data['Open'])
s2 = np.sum(a)
print(s2)

<class 'pandas.core.frame.DataFrame'>
         Date   Open   High    Low  Close  Volume
0  2020/07/01  315.0  318.0  314.0  317.5   29685
1  2020/07/02  319.0  322.0  318.0  322.0   37789
2  2020/07/03  327.0  330.5  326.5  329.5   55657
3  2020/07/06  332.5  338.0  332.0  338.0   57256
4  2020/07/07  343.5  346.0  338.0  338.5   59046

<class 'pandas.core.series.Series'>
0    315.0
1    319.0
2    327.0
3    332.5
4    343.5
Name: Open, dtype: float64

17585.5
17585.5


In [34]:
import pandas as pd


def info_of_month(_df, _year, _month):
    """Selection values by DateTime then print the informations of the table"""

    # Selecting values
    _df = _df.loc[str(_year) + "-" + str(_month).zfill(2)]

    # print informations
    print(int(_month), "月的", end="")
    print("平均股價為:", round(_df["Close"].mean(), 2), "元")
    print("當月的最高價為:  ", _df["High"].max(), "元")
    # print("  最低價為:", _df["Low"].min(), "元")
    print("本月成交量為:", _df["Volume"].sum(), "張")


def read_stock_data(ticker):
    """read the full data of the file as a """
    file_position = "2330.csv"
    _df = pd.read_csv(file_position,
                      index_col=0, parse_dates=True)
    return _df


def main():
    ticker = "2330"
    year = 2020
    for i in range(7, 9):
        info_of_month(read_stock_data(ticker), year, i)


if __name__ == "__main__":
    main()

7 月的平均股價為: 370.74 元
當月的最高價為:   466.5 元
本月成交量為: 1468402 張
8 月的平均股價為: 429.67 元
當月的最高價為:   453.5 元
本月成交量為: 1001180 張


In [37]:
# .zfill() 使用方式
num = 2
print(str(num).zfill(2))

02


In [48]:
import pandas as pd
# pd.read_csv(data, parse_dates=True) # 自動解析日期時間格式
_df = pd.read_csv('2330.csv',index_col=0, parse_dates=True)
print(_df.head())

# 選擇 index 中所有符合 2020-08 的資料 
_df = _df.loc[str(2020) + "-" + str('8').zfill(2)]
print(_df)

             Open   High    Low  Close  Volume
Date                                          
2020-07-01  315.0  318.0  314.0  317.5   29685
2020-07-02  319.0  322.0  318.0  322.0   37789
2020-07-03  327.0  330.5  326.5  329.5   55657
2020-07-06  332.5  338.0  332.0  338.0   57256
2020-07-07  343.5  346.0  338.0  338.5   59046
             Open   High    Low  Close  Volume
Date                                          
2020-08-03  420.5  424.0  415.0  416.0   77289
2020-08-04  421.5  425.5  418.5  425.5   41697
2020-08-05  430.5  433.5  426.0  429.0   47461
2020-08-06  437.5  438.0  431.0  435.0   43444
2020-08-07  433.5  434.0  428.0  433.0   37611
2020-08-10  427.5  437.5  427.5  435.5   36068
2020-08-11  432.0  435.0  429.0  429.0   34545
2020-08-12  422.0  423.5  419.0  419.0   53980
2020-08-13  428.0  429.0  424.5  429.0   45669
2020-08-14  424.0  428.0  423.0  427.0   24260
2020-08-17  427.0  435.0  425.5  435.0   34608
2020-08-18  440.0  440.5  432.0  433.0   45504
2020-08-19  4

In [65]:
pd.__version__

'1.3.3'

In [ ]:
import pandas as pd
pd.__version__
df = pd.read_csv('2330.csv') 

df1 = df[df['Date'].between('7/1/2020','7/31/2020')]
df1.column = df1['High']# 7月的最高價為
max_value = df1.column.max()

print(max_value)# 7月的最高價為
mean1 = df1['Close'].mean() #7 月的平均股價為
print(mean1)#7 月的平均股價為
df1.column = df1['Volume']#7月成交量為
sum1 = df1.column.sum()
print(sum1) #7月成交量為

df2 = df[df['Date'].between('8/1/2020','8/31/2020')]
df2
mean2 = df2['Close'].mean() #8 月的平均股價為
print(mean2)#8 月的平均股價為
df2.column = df2['High']# 8月的最高價為
max_value2 = df2.column.max()
print(max_value2)
df2.column = df2['Volume']#8月成交量為
sum2 = df2.column.sum()
print(sum2) #8月成交量為